# Generated by Django 5.1.1 on 2024-09-18 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='youtube_link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
    ]
